project:
  type: website

website:
  title: "公司网站"
  navbar:
    left:
      - href: index.qmd
        text: 主页
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



